#@host = https://ifmbsfe0dev-protocap.cfapps.eu20.hana.ondemand.com
# @host = http://ifmbsfe0dev.localhost:5000
@host = http://localhost:3000

# open https://ifmbsfe0dev-protocap.cfapps.eu20.hana.ondemand.com/api/hello in browser's
# debug mode to obtain the JSESSSIONID-Cookie
#@cookie = JSESSIONID=...
@cookie = JSESSIONID=s%3Aurvx_0lOf5McMeZcyyNbPidzNe4gwwqx.b33tmODCIPJBx%2BhP7nuFemoEb%2FDEx3DRaXIZOu6y4IQ

### Simple Controller/Approuter test
GET {{host}}/api/hello
Cookie: {{cookie}}

### OData Service root
GET {{host}}/odata/
Cookie: {{cookie}}

### OData Service Metadata
GET {{host}}/odata/$metadata
Cookie: {{cookie}}

### OData EntitySet
GET {{host}}/odata/Sample
Cookie: {{cookie}}

### OData EntitySet via SAP Backend
GET {{host}}/odata/Plants
Cookie: {{cookie}}

### Retrieve destination from service
GET {{host}}/api/destinationTest
Cookie: {{cookie}}

### Batch request
POST {{host}}/odata/$batch
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b 

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

GET /odata/Plants HTTP/1.1 


--batch_36522ad7-fc75-4b56-8c71-56071383e77b--

### Batch Request
POST {{host}}/odata/$batch
accept: multipart/mixed
content-type: multipart/mixed;boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b 
DataServiceVersion: 2.0 
MaxDataServiceVersion: 4.0 

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

GET odata/Plants HTTP/1.1

--batch_36522ad7-fc75-4b56-8c71-56071383e77b--

### 
GET http://localhost:3000/odata/Plants?
x-forwarded-host: ifmbsfe0dev.localhost  